export const CONFERENCE_INSERT_REQUEST = 'CONFERENCE_INSERT_REQUEST'
export const CONFERENCE_INSERT_SUCCESS = 'CONFERENCE_INSERT_SUCCESS'
export const CONFERENCE_INSERT_FAIL = 'CONFERENCE_INSERT_FAIL'

export const CONFERENCE_ALL_REQUEST = 'CONFERENCE_ALL_REQUEST'
export const CONFERENCE_ALL_SUCCESS = 'CONFERENCE_ALL_SUCCESS'
export const CONFERENCE_ALL_FAIL = 'CONFERENCE_ALL_FAIL'

export const CONFERENCE_BYID_REQUEST = 'CONFERENCE_BYID_REQUEST'
export const CONFERENCE_BYID_SUCCESS = 'CONFERENCE_BYID_SUCCESS'
export const CONFERENCE_BYID_FAIL = 'CONFERENCE_BYID_FAIL'