export const CONFERENCE_INSERT_REQUEST = 'CONFERENCE_INSERT_REQUEST'
export const CONFERENCE_INSERT_SUCCESS = 'CONFERENCE_INSERT_SUCCESS'
export const CONFERENCE_INSERT_FAIL = 'CONFERENCE_INSERT_FAIL'

export const CONFERENCE_ALL_REQUEST = 'CONFERENCE_ALL_REQUEST'
export const CONFERENCE_ALL_SUCCESS = 'CONFERENCE_ALL_SUCCESS'
export const CONFERENCE_ALL_FAIL = 'CONFERENCE_ALL_FAIL'

export const CONFERENCE_BYID_REQUEST = 'CONFERENCE_BYID_REQUEST'
export const CONFERENCE_BYID_SUCCESS = 'CONFERENCE_BYID_SUCCESS'
export const CONFERENCE_BYID_FAIL = 'CONFERENCE_BYID_FAIL'

export const CONFERENCE_DELETE_REQUEST = 'CONFERENCE_DELETE_REQUEST'
export const CONFERENCE_DELETE_SUCCESS = 'CONFERENCE_DELETE_SUCCESS'
export const CONFERENCE_DELETE_FAIL = 'CONFERENCE_DELETE_FAIL'

export const CONFERENCE_UPDATE_REQUEST = 'CONFERENCE_UPDATE_REQUEST'
export const CONFERENCE_UPDATE_SUCCESS = 'CONFERENCE_UPDATE_SUCCESS'
export const CONFERENCE_UPDATE_FAIL = 'CONFERENCE_UPDATE_FAIL'
export const CONFERENCE_UPDATE_RESET = 'CONFERENCE_UPDATE_RESET'

