export const CONFERENCE_INSERT_REQUEST = 'CONFERENCE_INSERT_REQUEST'
export const CONFERENCE_INSERT_SUCCESS = 'CONFERENCE_INSERT_SUCCESS'
export const CONFERENCE_INSERT_FAIL = 'CONFERENCE_INSERT_FAIL'

