export const FOODS_ALL_REQUEST = 'FOODS_ALL_REQUEST'
export const FOODS_ALL_SUCCESS = 'FOODS_ALL_SUCCESS'
export const FOODS_ALL_FAIL = 'FOODS_ALL_FAIL'


export const FOODS_CREATE_REQUEST = 'FOODS_CREATE_REQUEST'
export const FOODS_CREATE_SUCCESS = 'FOODS_CREATE_SUCCESS'
export const FOODS_CREATE_FAIL = 'FOODS_CREATE_FAIL'
export const FOODS_CREATE_RESET = 'FOODS_CREATE_RESET'

export const FOODS_DELETE_REQUEST = 'FOODS_DELETE_REQUEST'
export const FOODS_DELETE_SUCCESS = 'FOODS_DELETE_SUCCESS'
export const FOODS_DELETE_FAIL = 'FOODS_DELETE_FAIL'



export const FOODS_BYID_REQUEST = 'FOODS_BYID_REQUEST'
export const FOODS_BYID_SUCCESS = 'FOODS_BYID_SUCCESS'
export const FOODS_BYID_FAIL = 'FOODS_BYID_FAIL'