export const FOODS_ALL_REQUEST = 'FOODS_ALL_REQUEST'
export const FOODS_ALL_SUCCESS = 'FOODS_ALL_SUCCESS'
export const FOODS_ALL_FAIL = 'FOODS_ALL_FAIL'


export const FOODS_CREATE_REQUEST = 'FOODS_CREATE_REQUEST'
export const FOODS_CREATE_SUCCESS = 'FOODS_CREATE_SUCCESS'
export const FOODS_CREATE_FAIL = 'FOODS_CREATE_FAIL'
export const FOODS_CREATE_RESET = 'FOODS_CREATE_RESET'