
export const REST_ALL_REQUEST = 'REST_ALL_REQUEST'
export const REST_ALL_SUCCESS = 'REST_ALL_SUCCESS'
export const REST_ALL_FAIL = 'REST_ALL_FAIL'


export const REST_BYID_REQUEST = 'REST_BYID_REQUEST'
export const REST_BYID_SUCCESS = 'REST_BYID_SUCCESS'
export const REST_BYID_FAIL = 'REST_BYID_FAIL'


export const REST_CREATE_REQUEST = 'REST_CREATE_REQUEST'
export const REST_CREATE_SUCCESS = 'REST_CREATE_SUCCESS'
export const REST_CREATE_FAIL = 'REST_CREATE_FAIL'
export const REST_CREATE_RESET = 'REST_CREATE_RESET'

export const REST_DELETE_REQUEST = 'REST_DELETE_REQUEST'
export const REST_DELETE_SUCCESS = 'REST_DELETE_SUCCESS'
export const REST_DELETE_FAIL = 'REST_DELETE_FAIL'

export const REST_UPDATE_REQUEST = 'REST_UPDATE_REQUEST'
export const REST_UPDATE_SUCCESS = 'REST_UPDATE_SUCCESS'
export const REST_UPDATE_FAIL = 'REST_UPDATE_FAIL'
export const REST_UPDATE_RESET = 'REST_UPDATE_RESET'

