
export const REST_ALL_REQUEST = 'REST_ALL_REQUEST'
export const REST_ALL_SUCCESS = 'REST_ALL_SUCCESS'
export const REST_ALL_FAIL = 'REST_ALL_FAIL'


export const REST_BYID_REQUEST = 'REST_BYID_REQUEST'
export const REST_BYID_SUCCESS = 'REST_BYID_SUCCESS'
export const REST_BYID_FAIL = 'REST_BYID_FAIL'


export const REST_CREATE_REQUEST = 'REST_CREATE_REQUEST'
export const REST_CREATE_SUCCESS = 'REST_CREATE_SUCCESS'
export const REST_CREATE_FAIL = 'REST_CREATE_FAIL'
export const REST_CREATE_RESET = 'REST_CREATE_RESET'