export const ROOMS_ALL_REQUEST = 'ROOMS_ALL_REQUEST'
export const ROOMS_ALL_SUCCESS = 'ROOMS_ALL_SUCCESS'
export const ROOMS_ALL_FAIL = 'ROOMS_ALL_FAIL'

export const ROOMS_BYID_REQUEST = 'ROOMS_BYID_REQUEST'
export const ROOMS_BYID_SUCCESS = 'ROOMS_BYID_SUCCESS'
export const ROOMS_BYIDL_FAIL = 'ROOMS_BYID_FAIL'

export const ROOMS_POSTBYID_REQUEST = 'ROOMS_POSTBYID_REQUEST'
export const ROOMS_POSTBYID_SUCCESS = 'ROOMS_POSTBYID_SUCCESS'
export const ROOMS_POSTBYIDL_FAIL = 'ROOMS_POSTBYIDL_FAIL'

export const CREATE_ROOMS_REQUEST = 'CREATE_ROOMS_REQUEST'
export const CREATE_ROOMS_SUCCESS = 'CREATE_ROOMS_SUCCESS'
export const CREATE_ROOMS_FAIL = 'CREATE_ROOMS_FAIL'
export const CREATE_ROOMS_RESET = 'CREATE_ROOMS_RESET'


export const ROOMS_LIST_REQUEST = 'ROOMS_LIST_REQUEST'
export const ROOMS_LIST_SUCCESS = 'ROOMS_LIST_SUCCESS'
export const ROOMS_LIST_FAIL = 'ROOMS_LIST_FAIL'
export const ROOMS_LIST_RESET = 'ROOMS_LIST_RESET'

export const ROOMS_DELETE_REQUEST = 'ROOMS_DELETE_REQUEST'
export const ROOMS_DELETE_SUCCESS = 'ROOMS_DELETE_SUCCESS'
export const ROOMS_DELETE_FAIL = 'ROOMS_DELETE_FAIL'
export const ROOMS_DELETE_RESET = 'ROOMS_DELETE_RESET'

export const ROOMS_UPDATE_REQUEST = 'ROOMS_UPDATE_REQUEST'
export const ROOMS_UPDATE_SUCCESS = 'ROOMS_UPDATE_SUCCESS'
export const ROOMS_UPDATE_FAIL = 'ROOMS_UPDATE_FAIL'
export const ROOMS_UPDATE_RESET = 'ROOMS_UPDATE_RESET'