export const ROOMS_ALL_REQUEST = 'ROOMS_ALL_REQUEST'
export const ROOMS_ALL_SUCCESS = 'ROOMS_ALL_SUCCESS'
export const ROOMS_ALL_FAIL = 'ROOMS_ALL_FAIL'

export const ROOMS_BYID_REQUEST = 'ROOMS_BYID_REQUEST'
export const ROOMS_BYID_SUCCESS = 'ROOMS_BYID_SUCCESS'
export const ROOMS_BYIDL_FAIL = 'ROOMS_BYID_FAIL'

export const ROOMS_POSTBYID_REQUEST = 'ROOMS_POSTBYID_REQUEST'
export const ROOMS_POSTBYID_SUCCESS = 'ROOMS_POSTBYID_SUCCESS'
export const ROOMS_POSTBYIDL_FAIL = 'ROOMS_POSTBYIDL_FAIL'