export const TBOOKING_CREATE_REQUEST = 'TBOOKING_CREATE_REQUEST'
export const TBOOKING_CREATE_SUCCESS = 'TBOOKING_CREATE_SUCCESS'
export const TBOOKING_CREATE_FAIL = 'TBOOKING_CREATE_FAIL'
export const TBOOKING_CREATE_RESET = 'TBOOKING_CREATE_RESET'