export const TBOOKING_CREATE_REQUEST = 'TBOOKING_CREATE_REQUEST'
export const TBOOKING_CREATE_SUCCESS = 'TBOOKING_CREATE_SUCCESS'
export const TBOOKING_CREATE_FAIL = 'TBOOKING_CREATE_FAIL'
export const TBOOKING_CREATE_RESET = 'TBOOKING_CREATE_RESET'



export const TBOOKING_LIST_REQUEST = 'TBOOKING_LIST_REQUEST'
export const TBOOKING_LIST_SUCCESS = 'TBOOKING_LIST_SUCCESS'
export const TBOOKING_LIST_FAIL = 'TBOOKING_LIST_FAIL'