export const WEDDING_INSERT_REQUEST = 'WEDDING_INSERT_REQUEST'
export const WEDDING_INSERT_SUCCESS = 'WEDDING_INSERT_SUCCESS'
export const WEDDING_INSERT_FAIL = 'WEDDING_INSERT_FAIL'

export const WEDDING_ALL_REQUEST = 'WEDDING_ALL_REQUEST'
export const WEDDING_ALL_SUCCESS = 'WEDDING_ALL_SUCCESS'
export const WEDDING_ALL_FAIL = 'WEDDING_ALL_FAIL'