export const WEDDING_INSERT_REQUEST = 'WEDDING_INSERT_REQUEST'
export const WEDDING_INSERT_SUCCESS = 'WEDDING_INSERT_SUCCESS'
export const WEDDING_INSERT_FAIL = 'WEDDING_INSERT_FAIL'

export const WEDDING_ALL_REQUEST = 'WEDDING_ALL_REQUEST'
export const WEDDING_ALL_SUCCESS = 'WEDDING_ALL_SUCCESS'
export const WEDDING_ALL_FAIL = 'WEDDING_ALL_FAIL'

export const WEDDING_BYID_REQUEST = 'WEDDING_BYID_REQUEST'
export const WEDDING_BYID_SUCCESS = 'WEDDING_BYID_SUCCESS'
export const WEDDING_BYID_FAIL = 'WEDDING_BYID_FAIL'

export const WEDDING_DELETE_REQUEST = 'WEDDING_DELETE_REQUEST'
export const WEDDING_DELETE_SUCCESS = 'WEDDING_DELETE_SUCCESS'
export const WEDDING_DELETE_FAIL = 'WEDDING_DELETE_FAIL'

export const WEDDING_UPDATE_REQUEST = 'WEDDING_UPDATE_REQUEST'
export const WEDDING_UPDATE_SUCCESS = 'WEDDING_UPDATE_SUCCESS'
export const WEDDING_UPDATE_FAIL = 'WEDDING_UPDATE_FAIL'
export const WEDDING_UPDATE_RESET = 'WEDDING_UPDATE_RESET'
